### ISSUE TITLE
Autocomplete issue

### ISSUE THREAD

**Issue by sQVe** [zimfw/completion#10] opened 2022-06-20 14:42 UTC
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
When trying to `cd` into similar named directories it fails to autocomplete, sometimes.

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. `mkdir -p tmp/{users,utils}`
6. `cd tmp`
7. type `cd u` and then <kbd>Tab</kbd> to autocomplete.

**Current behavior** 
When pressing <kbd>Tab</kbd> it incorrectly autocompletes to `uT` and then `utils/` if you press <kbd>Tab</kbd> again.

**Expected behavior**  
It should give correct autocomplete, proving `users/` and `utils/` as options.

**Screenshots**  

https://user-images.githubusercontent.com/2284724/174626697-15c1f947-48d5-4ba9-93b1-0f8d159936d4.mp4

**zimfw info**  
```
zimfw version: 1.9.1 (built at 2022-05-24 21:25:10 UTC, previous commit is 5bcfb8c)
ZIM_HOME:      /home/sqve/.local/share/zim
Zsh version:   5.9
System info:   Linux calcifer 5.18.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 16 Jun 2022 20:40:45 +0000 x86_64 GNU/Linux
```

**Comment by ericbn** [comment] 2022-06-20 14:56
Hey @sQVe! Thanks for the detailed report! I was able to reproduce it in macOS too (which has a case insensitive file system), and even with `setopt caseglob`.

Our [`matcher-list` configuration](https://github.com/zimfw/completion/blob/6a78111576cd0c653e0fbeb1ead5d2de3b490440/init.zsh#L45) is known to be buggy. See a longer discussion in https://github.com/zimfw/zimfw/issues/212. Your example adds to the long list of expected behavior discussed in that issue.

@marlonrichert has figured out a great configuration for the completion system in https://github.com/marlonrichert/zsh-autocomplete/blob/main/scripts/.autocomplete.config. I haven't had time to explore the details of his implementation, but I believe we might be able to figure out the solution for a fuzzy completion like we expect based on his work.

**Comment by sQVe** [comment] 2022-06-20 14:59
I tried playing around with this module and if I unset `NO_CASE_GLOB` and comment out `zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' '+r:|?=**'` I get the correct completion for this case. I'm well aware that it isn't that simple but thought it might be worth noting.

**Comment by sQVe** [comment] 2022-06-20 15:17
I tried changing the `matcher-list` to https://github.com/marlonrichert/zsh-autocomplete/blob/4decd760641377e818d11146ef1249f5474c224a/scripts/.autocomplete.config#L64-L72 and that seems to work well, as far as I can tell.

**Comment by ericbn** [comment] 2022-06-20 15:22
Cool. I believe you'll also need an extra configuration to enable the loose and fuzzy matchers. This is done here: https://github.com/marlonrichert/zsh-autocomplete/blob/4decd760641377e818d11146ef1249f5474c224a/scripts/.autocomplete.config#L26-L33

**Comment by sQVe** [comment] 2022-06-20 15:38
I'm a bit unsure what the differences between the three are. Just setting:
```zsh
zstyle ':completion:*' matcher-list \
  'm:{[:lower:]-}={[:upper:]_} r:|[.]=**' \
  '+l:|=*'
```
Seems to work fine for my use-cases.

**Comment by marlonrichert** [comment] 2022-06-21 16:10
The documentation for Zsh completion matchers has been a mess for years. However, I recently wrote completely new documentation for it, which has been released with Zsh 5.9: https://zsh.sourceforge.io/Doc/Release/Completion-Widgets.html#Completion-Matching-Control

Hopefully, this makes things more clear.

(Note, however, that there are long-standing bugs in the `:||=` matchers. The docs that I wrote describe how they are _intended_ to work, but they don’t actually work like that at present. I would avoid them for now.)

**Comment by sQVe** [comment] 2022-06-21 17:20
@marlonrichert Cheers for great information! Could you possibly provide insight into what the matcher-list I'm using above actually does?

**Comment by marlonrichert** [comment] 2022-06-21 21:22
<dl>
<dt>

`m:{[:lower:]-}={[:upper:]_}`
</dt><dd>

Each lowercase letter in the input can also match its uppercase counterpart and each `-` in the input can also match a `_`.
</dd><dt>

`r:|[.]=**`
</dt><dt>

`r:|.=**`
</dt><dd>

Each empty substring in the input that has a `.` to the right of it can match any substring, including those containing other instances of `.`. (If you had just a single `*` there, then it couldn’t match substrings containing `.`) In other words, this inserts a wildcard to the left of each `.`.
</dd><dt>

`+`
</dt><dd>

If the previous matcher fails, then append this matcher to it and try again. (Note that this is unique to `zstyle […] matcher-list` and thus not handled in the chapter I linked to above. [See here](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Standard-Styles) instead.)
</dd><dt>

`l:|=*`
</dt><dd>

If there is an empty substring at the left edge of the input (which is by definition always the case), then it can match any substring. In other words, this adds a wildcard to the left edge of the input.
</dd>
</dl>

**Closed as completed** 2024-03-10 10:21 UTC
Labels: bug
